// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu6jjyqORqrAwLie6a0c6mFYGvWA7VjcQ',
    appId: '1:128648646339:android:8f957c57ba8d855f619c76',
    messagingSenderId: '128648646339',
    projectId: 'prodex-99aba',
    storageBucket: 'prodex-99aba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCitBxuls9YynYMpw0iJFmnZ2IAZj04QuY',
    appId: '1:128648646339:ios:64b6d728c3a66023619c76',
    messagingSenderId: '128648646339',
    projectId: 'prodex-99aba',
    storageBucket: 'prodex-99aba.firebasestorage.app',
    iosBundleId: 'com.example.mytaskapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHA4HL5TuWvETjwIuqIgJi3FM4Lx_fCFI',
    appId: '1:128648646339:web:dcc488af2be4167a619c76',
    messagingSenderId: '128648646339',
    projectId: 'prodex-99aba',
    authDomain: 'prodex-99aba.firebaseapp.com',
    storageBucket: 'prodex-99aba.firebasestorage.app',
  );

}